"""Filesystem paths and the shared generated-file header."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = REPO_ROOT / "src"
PACKAGE_INIT = SOURCE_ROOT / "quater" / "__init__.py"
REFERENCE_DIR = REPO_ROOT / "docs" / "en" / "dev" / "reference"
GENERATED_HEADER = (
    "<!-- Generated by scripts/generate_reference.py. Do not edit by hand. -->"
)
